port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
#external-ui: "/usr/share/openclash/ui/dashboard"
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5

#===================== OpenClash-General-Settings =====================#
proxies:
    



   
proxy-groups:
  - name: "ğŸš€Proxy"
    type: "select"  
    use:
     # - "ğŸ‡YToo"
      - "ğŸ‡chiguayun"
      
  - name: "ğŸš€sanfen"
    type: "select"  
    use:
      - "ğŸ‡YToo"
      #- "ğŸ‡chiguayun"       
      
  - name: "ğŸ’–Google"
    type: "select"
    proxies:
      #- "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-01"     
    use:     
      - "ğŸ‡chiguayun"  
      - "ğŸ‡YToo"      
    
  - name: "ğŸ¬ YouTube"
    type: "select"
    proxies:
      - "ç‹®åŸè‡ªåŠ¨"
      - "é¦™æ¸¯è‡ªåŠ¨"
      
      #- "ğŸš€Proxy"
      #- "ğŸš€sanfen"
    use:
     # - "ğŸ‡YToo"
      - "ğŸ‡chiguayun"
           
  - name: "ğŸ“¹TikTok"
    type: "select"
    proxies:
      - "é¦™æ¸¯è‡ªåŠ¨"
      #- "ğŸ’–Google" 
      #- "ğŸš€Proxy"
      #- "ğŸš€sanfen"        
    use:
      #- "ğŸ‡YToo"
      - "ğŸ‡chiguayun"   
          
  - name: "ğŸ“º BiliBili"
    type: "select"
    proxies:
      - "DIRECT"
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-é«˜é€Ÿå…¥å£"
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-é«˜é€Ÿå…¥å£"
      - "ğŸ‡­ğŸ‡°é¦™æ¸¯é«˜é€Ÿæ¥å…¥ç‚¹-01"
      - "å°æ¹¾é«˜é€Ÿæ¥å…¥ç‚¹-01"
           
    #use:è¿™ä¸ªæ˜¯æœç´¢chiguayunè®¢é˜…é“¾æ¥
     # - "ğŸ‡chiguayun"  
         
  - name: "ğŸ±â€ğŸ‘¤TG"
    type: "select"
    proxies:
      #- "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
      #- "ğŸš€Proxy"
      #- "ğŸš€sanfen"
    use:
     # - "ğŸ‡YToo" 
      - "ğŸ‡chiguayun"
      
           
  - name: "ğŸ¥ Netflix"
    type: "select"
    proxies:
      - "ğŸš€Proxy"
    use:
      - "ğŸ‡YToo"    
            
  - name: "ğŸ‘¸Disney+"
    type: "select"
    proxies:
      - "ğŸš€Proxy"
    use:
      - "ğŸ‡YToo"     
             
  - name: "ğŸ¬MI_NF"
    type: "select"
    proxies:
      - "DIRECT"
    use:
      - "ğŸ‡YToo"             
      
  - name: "ğŸ¤–openAI"
    type: "select"
    use:
      - "ğŸ‡YToo"  
      
  - name: "ğŸApple"
    type: "select"
    proxies:
      - "DIRECT"
      - "ğŸš€Proxy"       
      
  - name: "â˜GD"
    type: "select"
    proxies:
      - "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
    use:
      - "ğŸ‡YToo"
     
  - name: "â˜OD"
    type: "select"
    proxies:
      - "DIRECT"
    use:
      - "ğŸ‡YToo"
  
  - name: "ğŸ’»VPS"    
    type: "select"
    proxies:
      - "DIRECT"
    use:
      - "ğŸ‡YToo" 
        
  - name: "ğŸ’Šbd"
    type: "select"
    proxies:
      - "DIRECT"
    use:
      - "ğŸ‡YToo"            
             
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    proxies: 
      - "ğŸ‡¸ğŸ‡¬ SGæ–°åŠ å¡-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¸ğŸ‡¬ SGæ–°åŠ å¡-ä¼˜åŒ–å…¥å£"      
      - "ğŸ‡¯ğŸ‡µ JPæ—¥æœ¬-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¯ğŸ‡µ JPæ—¥æœ¬-ä¼˜åŒ–å…¥å£"      
      - "ğŸ‡ºğŸ‡¸ USAç¾å›½-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡ºğŸ‡¸ USAç¾å›½-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-é«˜é€Ÿå…¥å£"
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-ä¼˜åŒ–å…¥å£"     
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-ä¼˜åŒ–å…¥å£"           
      - "ğŸ‡¹ğŸ‡· TRåœŸè€³å…¶-é«˜é€Ÿå…¥å£"    
      - "ğŸ‡¹ğŸ‡· TRåœŸè€³å…¶-ä¼˜åŒ–å…¥å£"     
      - "ğŸ‡¬ğŸ‡§ UKè‹±å›½-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡¬ğŸ‡§ UKè‹±å›½-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡©ğŸ‡ª DEå¾·å›½-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡©ğŸ‡ª DEå¾·å›½-é«˜é€Ÿå…¥å£"          
      - "ğŸ‡®ğŸ‡³ INå°åº¦-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡®ğŸ‡³ INå°åº¦-é«˜é€Ÿå…¥å£"                                   
      - "ğŸ‡»ğŸ‡³ VNè¶Šå—-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡»ğŸ‡³ VNè¶Šå—-ä¼˜åŒ–å…¥å£"                      
      - "ğŸ‡³ğŸ‡± NLè·å…°-é«˜é€Ÿå…¥å£"
      - "ğŸ‡³ğŸ‡± NLè·å…°-ä¼˜åŒ–å…¥å£"      
      - "ğŸ‡µğŸ‡± PLæ³¢å…°-é«˜é€Ÿå…¥å£"     
      - "ğŸ‡µğŸ‡± PLæ³¢å…°-ä¼˜åŒ–å…¥å£"     
      - "ğŸ‡¨ğŸ‡­ CHç‘å£«-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¨ğŸ‡­ CHç‘å£«-ä¼˜åŒ–å…¥å£"     
      - "ğŸ‡¸ğŸ‡ª SEç‘å…¸-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¸ğŸ‡ª SEç‘å…¸-ä¼˜åŒ–å…¥å£"  
      - "ğŸ‡«ğŸ‡· FRæ³•å›½-é«˜é€Ÿå…¥å£"
      - "ğŸ‡«ğŸ‡· FRæ³•å›½-ä¼˜åŒ–å…¥å£"      
      - "ğŸ‡²ğŸ‡² MMç¼…ç”¸-é«˜é€Ÿå…¥å£"
      - "ğŸ‡²ğŸ‡² MMç¼…ç”¸-ä¼˜åŒ–å…¥å£"            
      - "ğŸ‡©ğŸ‡° Dkä¸¹éº¦-é«˜é€Ÿå…¥å£"
      - "ğŸ‡©ğŸ‡° Dkä¸¹éº¦-ä¼˜åŒ–å…¥å£"     
      - "ğŸ‡¬ğŸ‡· GRå¸Œè…Š-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¬ğŸ‡· GRå¸Œè…Š-ä¼˜åŒ–å…¥å£"      
      - "ğŸ‡³ğŸ‡´ NOæŒªå¨-é«˜é€Ÿå…¥å£"
      - "ğŸ‡³ğŸ‡´ NOæŒªå¨-ä¼˜åŒ–å…¥å£"        
      - "ğŸ‡¨ğŸ‡¦ CAåŠ æ‹¿å¤§-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡¨ğŸ‡¦ CAåŠ æ‹¿å¤§-é«˜é€Ÿå…¥å£"                    
      - "ğŸ‡·ğŸ‡º RUä¿„ç½—æ–¯-é«˜é€Ÿå…¥å£"
      - "ğŸ‡·ğŸ‡º RUä¿„ç½—æ–¯-ä¼˜åŒ–å…¥å£"      
    
  - name: ç‹®åŸè‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - "ğŸ‡¸ğŸ‡¬ SGæ–°åŠ å¡-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡¸ğŸ‡¬ SGæ–°åŠ å¡-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¸ğŸ‡¬æ–°åŠ å¡é«˜é€Ÿæ¥å…¥ç‚¹-01"
      - "ğŸ‡¸ğŸ‡¬æ–°åŠ å¡é«˜é€Ÿæ¥å…¥ç‚¹-02"
      - "ğŸ‡¸ğŸ‡¬æ–°åŠ å¡é«˜é€Ÿæ¥å…¥ç‚¹-02"
      
  - name: é¦™æ¸¯è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-é«˜é€Ÿå…¥å£"
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-ä¼˜åŒ–å…¥å£"
  - name: å°æ¹¾è‡ªåŠ¨
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-ä¼˜åŒ–å…¥å£" 
      
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:                   
      - "ğŸ‡¸ğŸ‡¬ SGæ–°åŠ å¡-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¸ğŸ‡¬ SGæ–°åŠ å¡-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¯ğŸ‡µ JPæ—¥æœ¬-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¯ğŸ‡µ JPæ—¥æœ¬-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡ºğŸ‡¸ USAç¾å›½-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡ºğŸ‡¸ USAç¾å›½-é«˜é€Ÿå…¥å£"
      
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-é«˜é€Ÿå…¥å£"
      - "ğŸ‡­ğŸ‡° HKé¦™æ¸¯-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¹ğŸ‡¼ TWå°æ¹¾-ä¼˜åŒ–å…¥å£"
           
      - "ğŸ‡¹ğŸ‡· TRåœŸè€³å…¶-é«˜é€Ÿå…¥å£"    
      - "ğŸ‡¹ğŸ‡· TRåœŸè€³å…¶-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¬ğŸ‡§ UKè‹±å›½-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡¬ğŸ‡§ UKè‹±å›½-é«˜é€Ÿå…¥å£"
      
      - "ğŸ‡©ğŸ‡ª DEå¾·å›½-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡©ğŸ‡ª DEå¾·å›½-é«˜é€Ÿå…¥å£"
           
      - "ğŸ‡®ğŸ‡³ INå°åº¦-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡®ğŸ‡³ INå°åº¦-é«˜é€Ÿå…¥å£"
                                    
      - "ğŸ‡»ğŸ‡³ VNè¶Šå—-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡»ğŸ‡³ VNè¶Šå—-ä¼˜åŒ–å…¥å£"
                       
      - "ğŸ‡³ğŸ‡± NLè·å…°-é«˜é€Ÿå…¥å£"
      - "ğŸ‡³ğŸ‡± NLè·å…°-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡µğŸ‡± PLæ³¢å…°-é«˜é€Ÿå…¥å£"     
      - "ğŸ‡µğŸ‡± PLæ³¢å…°-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¨ğŸ‡­ CHç‘å£«-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¨ğŸ‡­ CHç‘å£«-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¸ğŸ‡ª SEç‘å…¸-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¸ğŸ‡ª SEç‘å…¸-ä¼˜åŒ–å…¥å£"
   
      - "ğŸ‡«ğŸ‡· FRæ³•å›½-é«˜é€Ÿå…¥å£"
      - "ğŸ‡«ğŸ‡· FRæ³•å›½-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡²ğŸ‡² MMç¼…ç”¸-é«˜é€Ÿå…¥å£"
      - "ğŸ‡²ğŸ‡² MMç¼…ç”¸-ä¼˜åŒ–å…¥å£"
            
      - "ğŸ‡©ğŸ‡° Dkä¸¹éº¦-é«˜é€Ÿå…¥å£"
      - "ğŸ‡©ğŸ‡° Dkä¸¹éº¦-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¬ğŸ‡· GRå¸Œè…Š-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¬ğŸ‡· GRå¸Œè…Š-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡³ğŸ‡´ NOæŒªå¨-é«˜é€Ÿå…¥å£"
      - "ğŸ‡³ğŸ‡´ NOæŒªå¨-ä¼˜åŒ–å…¥å£"
        
      - "ğŸ‡¨ğŸ‡¦ CAåŠ æ‹¿å¤§-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡¨ğŸ‡¦ CAåŠ æ‹¿å¤§-é«˜é€Ÿå…¥å£"
                    
      - "ğŸ‡·ğŸ‡º RUä¿„ç½—æ–¯-é«˜é€Ÿå…¥å£"
      - "ğŸ‡·ğŸ‡º RUä¿„ç½—æ–¯-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡ºğŸ‡¦ UAä¹Œå…‹å…°-é«˜é€Ÿå…¥å£"
      - "ğŸ‡ºğŸ‡¦ UAä¹Œå…‹å…°-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡ªğŸ‡¸ ESè¥¿ç­ç‰™-é«˜é€Ÿå…¥å£"    
      - "ğŸ‡ªğŸ‡¸ ESè¥¿ç­ç‰™-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¦ğŸ‡ª AEé˜¿è”é…‹-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡¦ğŸ‡ª AEé˜¿è”é…‹-ä¼˜åŒ–å…¥å£"
              
      - "ğŸ‡¸ğŸ‡½ SXè²å¾‹å®¾-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¸ğŸ‡½ SXè²å¾‹å®¾-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¦ğŸ‡¹  ATå¥¥åœ°åˆ©-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¦ğŸ‡¹  ATå¥¥åœ°åˆ©-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡§ğŸ‡ª BEæ¯”åˆ©æ—¶-é«˜é€Ÿå…¥å£"
      - "ğŸ‡§ğŸ‡ª BEæ¯”åˆ©æ—¶-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡­ğŸ‡º HUåŒˆç‰™åˆ©-é«˜é€Ÿå…¥å£"
      - "ğŸ‡­ğŸ‡º HUåŒˆç‰™åˆ©-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡®ğŸ‡ª IEçˆ±å°”å…°-é«˜é€Ÿå…¥å£"
      - "ğŸ‡®ğŸ‡ª IEçˆ±å°”å…°-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡®ğŸ‡¹ ITæ„å¤§åˆ©-é«˜é€Ÿå…¥å£"
      - "ğŸ‡®ğŸ‡¹ ITæ„å¤§åˆ©-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡°ğŸ‡­ KHæŸ¬åŸ”å¯¨-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡°ğŸ‡­ KHæŸ¬åŸ”å¯¨-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡³ğŸ‡µ NPå°¼æ³Šå°”-é«˜é€Ÿå…¥å£"
      - "ğŸ‡³ğŸ‡µ NPå°¼æ³Šå°”-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¦ğŸ‡· ARé˜¿æ ¹å»·-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡¦ğŸ‡· ARé˜¿æ ¹å»·-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡¦ğŸ‡º AUæ¾³å¤§åˆ©äºš-ä¼˜åŒ–å…¥å£"
      - "ğŸ‡¦ğŸ‡º AUæ¾³å¤§åˆ©äºš-é«˜é€Ÿå…¥å£"
      
      - "ğŸ‡·ğŸ‡´ ROç½—é©¬å°¼äºš-é«˜é€Ÿå…¥å£"      
      - "ğŸ‡·ğŸ‡´ ROç½—é©¬å°¼äºš-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡§ğŸ‡¬ BGä¿åŠ åˆ©äºš-é«˜é€Ÿå…¥å£"
      - "ğŸ‡§ğŸ‡¬ BGä¿åŠ åˆ©äºš-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡µğŸ‡° PKå·´åŸºæ–¯å¦-é«˜é€Ÿå…¥å£"     
      - "ğŸ‡µğŸ‡° PKå·´åŸºæ–¯å¦-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡²ğŸ‡¾ MYé©¬æ¥è¥¿äºš-é«˜é€Ÿå…¥å£"
      - "ğŸ‡²ğŸ‡¾ MYé©¬æ¥è¥¿äºš-ä¼˜åŒ–å…¥å£"
              
      - "ğŸ‡§ğŸ‡© BDå­ŸåŠ æ‹‰å›½-é«˜é€Ÿå…¥å£"    
      - "ğŸ‡§ğŸ‡© BDå­ŸåŠ æ‹‰å›½-ä¼˜åŒ–å…¥å£"
            
      - "ğŸ‡·ğŸ‡¸ RSå¡å°”ç»´äºš-é«˜é€Ÿå…¥å£"
      - "ğŸ‡·ğŸ‡¸ RSå¡å°”ç»´äºš-ä¼˜åŒ–å…¥å£"
                 
      - "ğŸ‡¨ğŸ‡¿ CZæ·å…‹å…±å’Œå›½-é«˜é€Ÿå…¥å£"
      - "ğŸ‡¨ğŸ‡¿ CZæ·å…‹å…±å’Œå›½-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡°ğŸ‡¿ KZå“ˆè¨å…‹æ–¯å¦-é«˜é€Ÿå…¥å£"
      - "ğŸ‡°ğŸ‡¿ KZå“ˆè¨å…‹æ–¯å¦-ä¼˜åŒ–å…¥å£"
      
      - "ğŸ‡­ğŸ‡°é¦™æ¸¯é«˜é€Ÿæ¥å…¥ç‚¹-01"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-01"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-02"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-03"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-04"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-05"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-06"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-07"
      - "ğŸ‡ºğŸ‡¸ç¾å›½é«˜é€Ÿæ¥å…¥ç‚¹-08"      
      - "ğŸ‡¯ğŸ‡µæ—¥æœ¬é«˜é€Ÿæ¥å…¥ç‚¹-01"
      - "ğŸ‡¯ğŸ‡µæ—¥æœ¬é«˜é€Ÿæ¥å…¥ç‚¹-02"
      - "ğŸ‡¯ğŸ‡µæ—¥æœ¬é«˜é€Ÿæ¥å…¥ç‚¹-03"
      - "ğŸ‡¯ğŸ‡µæ—¥æœ¬é«˜é€Ÿæ¥å…¥ç‚¹-04"
      - "ğŸ‡¯ğŸ‡µæ—¥æœ¬é«˜é€Ÿæ¥å…¥ç‚¹-05"
      - "ğŸ‡¯ğŸ‡µæ—¥æœ¬é«˜é€Ÿæ¥å…¥ç‚¹-06"    
      - "ğŸ‡¸ğŸ‡¬æ–°åŠ å¡é«˜é€Ÿæ¥å…¥ç‚¹-01"
      - "ğŸ‡¸ğŸ‡¬æ–°åŠ å¡é«˜é€Ÿæ¥å…¥ç‚¹-02"
      - "ğŸ‡¸ğŸ‡¬æ–°åŠ å¡é«˜é€Ÿæ¥å…¥ç‚¹-02"
      - "å°æ¹¾é«˜é€Ÿæ¥å…¥ç‚¹-01"
  
  
         
proxy-providers:
  ğŸ‡YToo:
    type: http
    url: ""
    path: "./YToo/YToo.yaml"
    interval: 1800 
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204    
  
  ğŸ‡chiguayun:
    type: http
    url: ""
    path: "./chiguayun/chiguayun.yaml"
    interval: 1800 
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  
  
###################################################################################################################       
#è”ç½‘å¼•ç”¨è§„åˆ™
rule-providers:
  Reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/Reject.yaml
    interval: 86400

  OpenAI:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml"
    path: ./ruleset/OpenAI.yaml
    interval: 86400
  
  Google:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400
  
  OneDrive:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml"
    path: ./ruleset/OneDrive.yaml
    interval: 86400

  Proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/Proxy.yaml
    interval: 86400
  
  
  DisneyPlus:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/DisneyPlus.yaml"
    path: ./ruleset/DisneyPlus.yaml
    interval: 86400  

  HBO:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/HBO.yaml"
    path: ./ruleset/HBO.yaml
    interval: 86400  

  #https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml
  Bilibili:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/lovecxe/wkylove/main/clash/BilibiliHMT.yaml"
    path: ./ruleset/Bilibili.yaml
    interval: 86400  

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400    

  WeChat:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Wechat.yaml"
    path: ./ruleset/WeChat.yaml
    interval: 86400    
  
  SteamCN:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml"
    path: ./ruleset/SteamCN.yaml
    interval: 86400  
  
  Steam:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Steam.yaml"
    path: ./ruleset/Steam.yaml
    interval: 86400  
    
  Xbox:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Xbox.yaml"
    path: ./ruleset/Xbox.yaml
    interval: 86400  

  Apple:
    type: http
    behavior: domain 
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/Apple.yaml
    interval: 86400  
  
  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  Direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/Direct.yaml
    interval: 86400
  
  Private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/Private.yaml
    interval: 86400
  
  GFW:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/GFW.yaml
    interval: 86400
  
  GreatFire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/GreatFire.yaml
    interval: 86400
  
  #éä¸­å›½å¤§é™†ä½¿ç”¨çš„é¡¶çº§åŸŸååˆ—è¡¨
  Tld-Not-CN: 
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/Tld-Not-CN.yaml
    interval: 86400

  TelegramCidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/TelegramCidr.yaml
    interval: 86400
  
  #ä¸­å›½å¤§é™† IP åœ°å€åˆ—è¡¨
  CnCidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/CnCidr.yaml
    interval: 86400
  
  #å±€åŸŸç½‘ IP åŠä¿ç•™ IP åœ°å€åˆ—è¡¨
  LanCidr:
     type: http
     behavior: ipcidr
     url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
     path: ./ruleset/LanCidr.yaml
     interval: 86400
  

# è§„åˆ™
rules:
  # è‡ªå®šä¹‰è§„åˆ™
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN-KEYWORD,now.cc,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN-SUFFIX,youngqfbr-my.sharepoint.com,â˜OD
  - DOMAIN-SUFFIX,qiuyi-my.sharepoint.com,â˜OD
  - DOMAIN-SUFFIX,gyvtcedu-my.sharepoint.cn,â˜OD
  - DOMAIN-SUFFIX,datasd-my.sharepoint.com,â˜OD
  - DOMAIN-KEYWORD,sharepoint.com,â˜OD
  - DOMAIN-KEYWORD,onedrive,â˜OD
  - DOMAIN-SUFFIX,googleapis.com,â˜GD
  - IP-CIDR,172.217.160.106/32,â˜GD
  - SRC-IP-CIDR,192.168.1.198/32,ğŸ¬MI_NF
  - PROCESS-NAME,com.ss.android.ugc.trill,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,byteoversea.com,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,ibytedtos.com,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,ipstatp.com,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,muscdn.com,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,musical.ly,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,tiktok.com,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,tiktokcdn.com,ğŸ“¹TikTok
  - DOMAIN-SUFFIX,tiktokv.com,ğŸ“¹TikTok
  - DOMAIN-KEYWORD,-tiktokcdn-com,ğŸ“¹TikTok
  - DOMAIN-KEYWORD,tophup.today,ğŸš€Proxy
  - DOMAIN-KEYWORD,cli.im,DIRECT

  # iosç«¯OpenAIè§„åˆ™
  #- DOMAIN-KEYWORD,openai.com,ğŸ¤–openAI
  #- DOMAIN-KEYWORD,statsig.com,ğŸ¤–openAI
  #- DOMAIN-KEYWORD,revenuecat.com,ğŸ¤–openAI
  #- DOMAIN-KEYWORD,sentry.io,ğŸ¤–openAI


  # bdä¸é™é€Ÿè§„åˆ™
  - DOMAIN-KEYWORD,juyovo.com,ğŸ’Šbd
  - DOMAIN-KEYWORD,94speed.com,ğŸ’Šbd
  - DOMAIN-KEYWORD,binglengdexiwang.top,ğŸ’Šbd
  - IP-CIDR,139.9.95.121/32,ğŸ’Šbd
  
  # aws server rule
  - IP-CIDR,18.163.116.27/32,ğŸ’»VPS,no-resolve
  - IP-CIDR,143.42.76.210/32,ğŸ’»VPS,no-resolve
  - IP-CIDR,172.104.32.79/32,ğŸ’»VPS,no-resolve
  - DOMAIN-KEYWORD,archer.now.cc,ğŸ’»VPS,no-resolve

  # è§„åˆ™é›†å‘½ä¸­è§„åˆ™ 
  #- RULE-SET,Reject,REJECT
  - RULE-SET,Google,ğŸ’–Google
  - RULE-SET,YouTube,ğŸ¬ YouTube
  - RULE-SET,Netflix,ğŸ¥ Netflix
  - RULE-SET,HBO,ğŸ¥ Netflix
  - RULE-SET,OneDrive,â˜OD
  - RULE-SET,DisneyPlus,ğŸ‘¸Disney+
  - RULE-SET,Apple,ğŸApple
  - RULE-SET,OpenAI,ğŸ¤–openAI

  - RULE-SET,Steam,ğŸš€Proxy
  - RULE-SET,Xbox,ğŸš€Proxy
  - RULE-SET,Proxy,ğŸš€Proxy
  - RULE-SET,GFW,ğŸš€Proxy
  - RULE-SET,GreatFire,ğŸš€Proxy
  - RULE-SET,Tld-Not-CN,ğŸš€Proxy
  - RULE-SET,TelegramCidr,ğŸ±â€ğŸ‘¤TG

  #- RULE-SET,Bilibili,DIRECT
  - RULE-SET,Bilibili,ğŸ“º BiliBili
  - RULE-SET,icloud,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Private,DIRECT
  - RULE-SET,WeChat,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,NetEaseMusic,DIRECT
  - RULE-SET,CnCidr,DIRECT
  - RULE-SET,LanCidr,DIRECT

  # å…¶å®ƒè§„åˆ™ 
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€Proxy
